# Pipeline Project

You will be using the provided data to create a machine learning model pipeline.

You must handle the data appropriately in your pipeline to predict whether an
item is recommended by a customer based on their review.
Note the data includes numerical, categorical, and text data.

You should ensure you properly train and evaluate your model.

## The Data

The dataset has been anonymized and cleaned of missing values.

There are 8 features for to use to predict whether a customer recommends or does
not recommend a product.
The `Recommended IND` column gives whether a customer recommends the product
where `1` is recommended and a `0` is not recommended.
This is your model's target/

The features can be summarized as the following:

- **Clothing ID**: Integer Categorical variable that refers to the specific piece being reviewed.
- **Age**: Positive Integer variable of the reviewers age.
- **Title**: String variable for the title of the review.
- **Review Text**: String variable for the review body.
- **Positive Feedback Count**: Positive Integer documenting the number of other customers who found this review positive.
- **Division Name**: Categorical name of the product high level division.
- **Department Name**: Categorical name of the product department name.
- **Class Name**: Categorical name of the product class name.

The target:
- **Recommended IND**: Binary variable stating where the customer recommends the product where 1 is recommended, 0 is not recommended.

## Load Data

In [1]:
import pandas as pd

# Load data
df = pd.read_csv(
    'data/reviews.csv',
)

df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 18442 entries, 0 to 18441
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Clothing ID              18442 non-null  int64
 1   Age                      18442 non-null  int64
 2   Title                    18442 non-null  str
 3   Review Text              18442 non-null  str
 4   Positive Feedback Count  18442 non-null  int64
 5   Division Name            18442 non-null  str
 6   Department Name          18442 non-null  str
 7   Class Name               18442 non-null  str
 8   Recommended IND          18442 non-null  int64
dtypes: int64(4), str(5)
memory usage: 1.3 MB

,Clothing ID,Age,Title,Review Text,Positive Feedback Count,Division Name,Department Name,Class Name,Recommended IND
0,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,0,General,Dresses,Dresses,0
1,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",0,General Petite,Bottoms,Pants,1
2,847,47,Flattering shirt,This shirt is very flattering to all due to th...,6,General,Tops,Blouses,1
3,1080,49,Not for the very petite,"I love tracy reese dresses, but this one is no...",4,General,Dresses,Dresses,0
4,858,39,Cagrcoal shimmer fun,I aded this in my basket at hte last mintue to...,1,General Petite,Tops,Knits,1

## Preparing features (`X`) & target (`y`)

In [2]:
data = df

# separate features from labels
X = data.drop('Recommended IND', axis=1)
y = data['Recommended IND'].copy()

print('Labels:', y.unique())
print('Features:')
display(X.head())

Labels: [0 1]
Features:

,Clothing ID,Age,Title,Review Text,Positive Feedback Count,Division Name,Department Name,Class Name
0,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,0,General,Dresses,Dresses
1,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",0,General Petite,Bottoms,Pants
2,847,47,Flattering shirt,This shirt is very flattering to all due to th...,6,General,Tops,Blouses
3,1080,49,Not for the very petite,"I love tracy reese dresses, but this one is no...",4,General,Dresses,Dresses
4,858,39,Cagrcoal shimmer fun,I aded this in my basket at hte last mintue to...,1,General Petite,Tops,Knits

In [3]:
# Split data into train and test sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.1,
    shuffle=True,
    random_state=27,
)

# Your Work

## Data Exploration

Let's look at the numerical and categorical features first.

In [4]:
df['Clothing ID'].value_counts()

Clothing ID
1078    871
862     658
1094    651
1081    487
829     452
       ...
1188      1
271       1
7         1
55        1
631       1
Name: count, Length: 531, dtype: int64

In [5]:
df['Age'].describe()

count    18442.000000
mean        43.383635
std         12.246264
min         18.000000
25%         34.000000
50%         41.000000
75%         52.000000
max         99.000000
Name: Age, dtype: float64

In [6]:
df['Positive Feedback Count'].describe()

count    18442.000000
mean         2.697484
std          5.942220
min          0.000000
25%          0.000000
50%          1.000000
75%          3.000000
max        122.000000
Name: Positive Feedback Count, dtype: float64

In [7]:
df['Division Name'].value_counts()

Division Name
General           11664
General Petite     6778
Name: count, dtype: int64

In [8]:
df['Department Name'].value_counts()

Department Name
Tops        8713
Dresses     5371
Bottoms     3184
Jackets      879
Intimate     188
Trend        107
Name: count, dtype: int64

In [9]:
df['Class Name'].value_counts()

Class Name
Dresses           5371
Knits             3981
Blouses           2587
Sweaters          1218
Pants             1157
Jeans              970
Fine gauge         927
Skirts             796
Jackets            598
Outerwear          281
Shorts             260
Lounge             188
Trend              107
Casual bottoms       1
Name: count, dtype: int64

### Intermediate Resume

*Division Name* doesn't seem particularly useful with just two values. On the other hand, *Clothing ID* seems very relevant: good items would tend to get more favorable reviews and thus be recommended more often than bad items. Let's test this out by just looking at the DataFrame *Recommended IND* and *Positive Feedback Count* grouped by relevant *Clothing ID*.

In [10]:
most_reviewed_clothing_ids = df['Clothing ID'].value_counts()[:5]

df[df['Clothing ID'].isin(most_reviewed_clothing_ids.index)].groupby('Clothing ID')[['Recommended IND', 'Positive Feedback Count']].describe()

            Recommended IND                                               \
                      count      mean       std  min  25%  50%  75%  max
Clothing ID
829                   452.0  0.825221  0.380199  0.0  1.0  1.0  1.0  1.0
862                   658.0  0.811550  0.391368  0.0  1.0  1.0  1.0  1.0
1078                  871.0  0.811711  0.391168  0.0  1.0  1.0  1.0  1.0
1081                  487.0  0.852156  0.355310  0.0  1.0  1.0  1.0  1.0
1094                  651.0  0.818740  0.385529  0.0  1.0  1.0  1.0  1.0

            Positive Feedback Count                                          \
                              count      mean       std  min  25%  50%  75%
Clothing ID
829                           452.0  2.457965  4.541067  0.0  0.0  1.0  3.0
862                           658.0  2.583587  5.362918  0.0  0.0  0.5  2.0
1078                          871.0  2.859931  7.288229  0.0  0.0  1.0  3.0
1081                          487.0  3.203285  7.379885  0.0  0.0  1.0  3.0
1094                          651.0  3.480799  7.883431  0.0  0.0  1.0  3.0


              max
Clothing ID
829          44.0
862          43.0
1078         98.0
1081         81.0
1094         89.0

It seems our intuition was correct: good items tend to be recommended a lot. Similarly, we might expect that people who took the time to write the first review tend to recommend the product, because anecdotally, people don't tend to waste further time on bad items with the possible exception to warn others if the items is truly terrible.

In [11]:
least_reviewed_clothing_ids = df['Clothing ID'].value_counts()[-5:]
df[df['Clothing ID'].isin(least_reviewed_clothing_ids.index)].groupby('Clothing ID')[['Recommended IND', 'Positive Feedback Count']].describe()

            Recommended IND                                    \
                      count mean std  min  25%  50%  75%  max
Clothing ID
7                       1.0  1.0 NaN  1.0  1.0  1.0  1.0  1.0
55                      1.0  1.0 NaN  1.0  1.0  1.0  1.0  1.0
271                     1.0  1.0 NaN  1.0  1.0  1.0  1.0  1.0
631                     1.0  1.0 NaN  1.0  1.0  1.0  1.0  1.0
1188                    1.0  1.0 NaN  1.0  1.0  1.0  1.0  1.0

            Positive Feedback Count
                              count  mean std   min   25%   50%   75%   max
Clothing ID
7                               1.0   0.0 NaN   0.0   0.0   0.0   0.0   0.0
55                              1.0   0.0 NaN   0.0   0.0   0.0   0.0   0.0
271                             1.0  13.0 NaN  13.0  13.0  13.0  13.0  13.0
631                             1.0   0.0 NaN   0.0   0.0   0.0   0.0   0.0
1188                            1.0   0.0 NaN   0.0   0.0   0.0   0.0   0.0

Let's see if we can find at least one terrible item, where the single reviewer went out of their way to warn others.

In [12]:
# let's get value counts
value_counts = df['Clothing ID'].value_counts()
# limit to the first 100 with 1 review
single_review_clothing_ids = value_counts[value_counts == 1][:100]

single_review_clothing = df[df['Clothing ID'].isin(single_review_clothing_ids.index)]

single_review_clothing['Recommended IND'].value_counts()

Recommended IND
1    83
0    17
Name: count, dtype: int64

Let's look for a few example terrible items.

In [13]:
single_review_clothing[single_review_clothing['Recommended IND'] == 0]

,Clothing ID,Age,Title,Review Text,Positive Feedback Count,Division Name,Department Name,Class Name,Recommended IND
1567,63,33,Extra fabric,There is a lot of fabric here! the legs fit me...,0,General,Bottoms,Shorts,0
2004,18,42,Disappointing quality,"I ordered these leggings and loved them, for a...",0,General Petite,Bottoms,Jeans,0
2232,429,23,Pretty but poor quality,When these shorts arrived i loved them and was...,3,General,Bottoms,Shorts,0
3258,1064,46,I wanted to love it.,I read the other reviews before i purchased th...,0,General,Bottoms,Pants,0
5625,1023,57,Beautiful but runs huge,I was so glad to find such a beautiful item ma...,2,General,Bottoms,Jeans,0
5808,894,41,Disapppointed,Was excited about this sweater but it really d...,1,General,Tops,Fine gauge,0
9194,693,51,Awkward fit,I was so excited to try these on at my local r...,0,General Petite,Intimate,Lounge,0
9511,734,39,Beautiful but sheer,These pajama pants are beautiful but very shee...,0,General Petite,Intimate,Lounge,0
10768,669,21,Pretty but cheap,These are light and airy and pretty. they also...,6,General Petite,Intimate,Lounge,0
11263,1073,37,Sad this couldn't come home with me....,So i really loved this dress. i am tall (6ft) ...,7,General Petite,Dresses,Dresses,0
11787,1127,29,Odd shaped coat with stripped bands sewn in,Ordered a size medium as i usually take a medi...,10,General,Jackets,Outerwear,0
11825,1200,24,Its worth the sale price if you know your size,Bought this dress without trying it on but lis...,0,General,Dresses,Dresses,0
12145,11,46,Wanted to love it,The color says red but it's more like a rust. ...,0,General,Bottoms,Jeans,0
14866,673,38,Paper thin,"Great print, terrible quality. the material is...",1,General Petite,Intimate,Lounge,0
15310,559,73,"Great fabric, but runs small","Love the look of this and the fabric, but runs...",14,General,Trend,Trend,0
15316,982,26,Beautiful color but strange texture,I wanted to love this kimono...it is such a be...,2,General,Jackets,Jackets,0
16474,913,74,Runs short,I really wanted to love this sweater however i...,2,General,Tops,Fine gauge,0

## Building Pipeline

First, determine which features are *text*, requiring natural language processing (NLP), *categorical*, requiring encoding, or *numerical* requiring scaling.

In [14]:
text_features = ('Title', 'Review Text')
cat_features = ('Clothing ID', 'Division Name', 'Department Name', 'Class Name')
num_features = ('Positive Feedback Count', 'Age')

Next, let's build a few basic classes to assist in natural language processing (NLP).

In [15]:
from collections.abc import Collection
from sklearn.base import BaseEstimator, TransformerMixin
import spacy

class CharCounter(BaseEstimator, TransformerMixin):

    def __init__(self, character: str):
        """Character Counter Class

        Args:
            character: character to count in the text.
        """
        self.character = character

    def fit(self, X, y=None):
        """Fit to Data (NOP)"""
        self.is_fitted_ = True
        return self

    def transform(self, X):
        """Transform Data
        
        Args:
            X: array-like of shape (n_samples, n_features) input samples.
        
        Returns:
            array-like of shape (n_samples, n_features) transformed samples.
        """
        return [[x.count(self.character)] for x in X]

class SentimentAnalysis(BaseEstimator, TransformerMixin):
    def __init__(self, nlp: spacy.Language, pos: Collection[str]):
        """Sentiment Analysis
        
        Args:
            nlp: spacy Language model.
            pos: collection of part-of-speech tags to consider for sentiment
                 analysis, e.g. 'NOUN', 'ADJ' etc.
        """
        self.nlp = nlp
        self.pos = pos
    
    def fit(self, X, y=None):
        """Fit to Data (NOP)"""
        self.is_fitted_ = True
        return self

    def transform(self, X):
        """Transform Data
        
        Args:
            X: array-like of shape (n_samples, n_features) input samples.
        
        Returns:
            list[str]: one lemmatized document string per sample.
        """
        return [
            ' '.join(token.lemma_ for token in doc if token.pos_ in self.pos)
            for doc in self.nlp.pipe(X)
        ]

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import FunctionTransformer, MinMaxScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import FeatureUnion, Pipeline
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import numpy as np

# load English Core Web Small model
nlp = spacy.load('en_core_web_sm')

def _combine_text(X: pd.DataFrame) -> 'np.ndarray':
    """Combine text features into a single feature.

    Args:
        X: DataFrame with text features.

    Returns:
        np.ndarray: Combined text features.
    """
    return X.fillna("").astype(str).agg(' '.join, axis=1).to_numpy()

features = ColumnTransformer([
    ('txt', Pipeline([
        ('combine',  FunctionTransformer(_combine_text, validate=False)),
        ('features', FeatureUnion([
            ('chars',       CharCounter(character='')), # technically, off-by-one '' => 1 etc.
            ('spaces',      CharCounter(character=' ')),
            ('exclamation', CharCounter(character='!')),
            ('question',    CharCounter(character='?')),
            ('sentiment',   Pipeline([
                ('nlp',         SentimentAnalysis(nlp, ('NOUN', 'VERB', 'ADJ', 'ADV'))),
                ('tf-idf',      TfidfVectorizer()),
            ])),
        ])),
    ]), text_features),
    ('cat', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), cat_features),
    #('cat', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), cat_features),
    ('num', MinMaxScaler(feature_range=(0, 1), clip=True), num_features),
])

## Training Pipeline

In [17]:
from sklearn.ensemble import RandomForestClassifier

parameters = {
    'n_estimators': 100,
    'criterion':    'gini',
    'max_depth':    None,
    'max_features': 'sqrt',
    'max_samples':  None,
    'random_state':  0x2f905959,
    'n_jobs':       -1,
    'verbose':      False,
}

model = Pipeline([
    ('features', features),
    ('classifier', RandomForestClassifier(**parameters)),
])

In [18]:
model.fit(X_train, y_train)

Pipeline(steps=[('features',
                 ColumnTransformer(transformers=[('txt',
                                                  Pipeline(steps=[('combine',
                                                                   FunctionTransformer(func=<function _combine_text at 0x00000261DC07BCE0>)),
                                                                  ('features',
                                                                   FeatureUnion(transformer_list=[('chars',
                                                                                                   CharCounter(character='')),
                                                                                                  ('spaces',
                                                                                                   CharCounter(character=' ')),
                                                                                                  ('exclamation',
                                                                                                   CharCounter(character='!')),
                                                                                                  ('question',
                                                                                                   CharCounter(ch...
                                                                                                                                           'ADV'))),
                                                                                                                   ('tf-idf',
                                                                                                                    TfidfVectorizer())]))]))]),
                                                  ('Title', 'Review Text')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ('Clothing ID',
                                                   'Division Name',
                                                   'Department Name',
                                                   'Class Name')),
                                                 ('num',
                                                  MinMaxScaler(clip=True),
                                                  ('Positive Feedback Count',
                                                   'Age'))])),
                ('classifier',
                 RandomForestClassifier(n_jobs=-1, random_state=797989209,
                                        verbose=False))])

Evaluate trained model for accuracy:

In [19]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print('Accuracy:', accuracy)

Accuracy: 0.851490514905149

That's ~85.15% accuracy on first try, which seems really good.

## Fine-Tuning Pipeline

Let's now perform a grid search over relevant Random Forest and pre-processing pipeline parameters.

In [20]:
list(model.get_params().keys())

['memory',
 'steps',
 'transform_input',
 'verbose',
 'features',
 'classifier',
 'features__n_jobs',
 'features__remainder',
 'features__sparse_threshold',
 'features__transformer_weights',
 'features__transformers',
 'features__verbose',
 'features__verbose_feature_names_out',
 'features__txt',
 'features__cat',
 'features__num',
 'features__txt__memory',
 'features__txt__steps',
 'features__txt__transform_input',
 'features__txt__verbose',
 'features__txt__combine',
 'features__txt__features',
 'features__txt__combine__accept_sparse',
 'features__txt__combine__check_inverse',
 'features__txt__combine__feature_names_out',
 'features__txt__combine__func',
 'features__txt__combine__inv_kw_args',
 'features__txt__combine__inverse_func',
 'features__txt__combine__kw_args',
 'features__txt__combine__validate',
 'features__txt__features__n_jobs',
 'features__txt__features__transformer_list',
 'features__txt__features__transformer_weights',
 'features__txt__features__verbose',
 'features__txt__features__verbose_feature_names_out',
 'features__txt__features__chars',
 'features__txt__features__spaces',
 'features__txt__features__exclamation',
 'features__txt__features__question',
 'features__txt__features__sentiment',
 'features__txt__features__chars__character',
 'features__txt__features__spaces__character',
 'features__txt__features__exclamation__character',
 'features__txt__features__question__character',
 'features__txt__features__sentiment__memory',
 'features__txt__features__sentiment__steps',
 'features__txt__features__sentiment__transform_input',
 'features__txt__features__sentiment__verbose',
 'features__txt__features__sentiment__nlp',
 'features__txt__features__sentiment__tf-idf',
 'features__txt__features__sentiment__nlp__nlp',
 'features__txt__features__sentiment__nlp__pos',
 'features__txt__features__sentiment__tf-idf__analyzer',
 'features__txt__features__sentiment__tf-idf__binary',
 'features__txt__features__sentiment__tf-idf__decode_error',
 'features__txt__features__sentiment__tf-idf__dtype',
 'features__txt__features__sentiment__tf-idf__encoding',
 'features__txt__features__sentiment__tf-idf__input',
 'features__txt__features__sentiment__tf-idf__lowercase',
 'features__txt__features__sentiment__tf-idf__max_df',
 'features__txt__features__sentiment__tf-idf__max_features',
 'features__txt__features__sentiment__tf-idf__min_df',
 'features__txt__features__sentiment__tf-idf__ngram_range',
 'features__txt__features__sentiment__tf-idf__norm',
 'features__txt__features__sentiment__tf-idf__preprocessor',
 'features__txt__features__sentiment__tf-idf__smooth_idf',
 'features__txt__features__sentiment__tf-idf__stop_words',
 'features__txt__features__sentiment__tf-idf__strip_accents',
 'features__txt__features__sentiment__tf-idf__sublinear_tf',
 'features__txt__features__sentiment__tf-idf__token_pattern',
 'features__txt__features__sentiment__tf-idf__tokenizer',
 'features__txt__features__sentiment__tf-idf__use_idf',
 'features__txt__features__sentiment__tf-idf__vocabulary',
 'features__cat__categories',
 'features__cat__drop',
 'features__cat__dtype',
 'features__cat__feature_name_combiner',
 'features__cat__handle_unknown',
 'features__cat__max_categories',
 'features__cat__min_frequency',
 'features__cat__sparse_output',
 'features__num__clip',
 'features__num__copy',
 'features__num__feature_range',
 'classifier__bootstrap',
 'classifier__ccp_alpha',
 'classifier__class_weight',
 'classifier__criterion',
 'classifier__max_depth',
 'classifier__max_features',
 'classifier__max_leaf_nodes',
 'classifier__max_samples',
 'classifier__min_impurity_decrease',
 'classifier__min_samples_leaf',
 'classifier__min_samples_split',
 'classifier__min_weight_fraction_leaf',
 'classifier__monotonic_cst',
 'classifier__n_estimators',
 'classifier__n_jobs',
 'classifier__oob_score',
 'classifier__random_state',
 'classifier__verbose',
 'classifier__warm_start']

In [23]:
from sklearn.base import clone
from sklearn.model_selection import RandomizedSearchCV

estimator = clone(model)

params = dict(
    features__txt__features__sentiment__nlp__pos = [('NOUN', 'VERB', 'ADJ', 'ADV'), ('NOUN', 'ADJ'), ('VERB', 'ADV'), ('ADJ', 'ADV')],
    classifier__criterion = ['gini', 'entropy', 'log_loss'],
    classifier__n_estimators = [100, 150, 200, 250],
    classifier__max_depth = [None, 50, 100, 150],
    classifier__max_features = ['sqrt', 'log2', 0.5, 0.75, 1.0],
    classifier__max_samples = [None, 0.5, 0.75, 1.0],
)

search = RandomizedSearchCV(
    estimator,
    params,
    n_iter=10,    # Try 10 different combinations of parameters
    cv=3,         # Use 3-fold cross-validation
    refit=True,   # Refit the model using the best parameters found
    n_jobs=-1,    # Use all available processors (for multiprocessing)
    verbose=3,    # Output of parameters, score, time
    random_state=0x2f905959,
)
search.fit(X_train, y_train)

search.best_params_

Fitting 3 folds for each of 10 candidates, totalling 30 fits

{'features__txt__features__sentiment__nlp__pos': ('NOUN',
  'VERB',
  'ADJ',
  'ADV'),
 'classifier__n_estimators': 150,
 'classifier__max_samples': 1.0,
 'classifier__max_features': 0.5,
 'classifier__max_depth': 100,
 'classifier__criterion': 'gini'}

In [ ]:
y_pred_best = search.best_estimator_.predict(X_test)
accuracy_best = accuracy_score(y_test, y_pred_best)

print('Accuracy:', accuracy_best)

Accuracy: 0.8737127371273713

Well, ~87.37% is a modest improvement over the baseline.

In [24]:
from pathlib import Path
import joblib

filename = Path('model.joblib')
joblib.dump(model, filename )

print(f'Model saved to {filename}')

Model saved to model.joblib